InitParticles:
  - lattice:
      cell: fcc
      spacing: 2.1925
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 17.328
    - 17.328
    - 20
  T: 1.5641
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.1
      - PiecewiseLinear:
          E1: -1.0187
          E2: -1.3737
          d: 2
          pos1: 0.76
          pos2: 3.5
      - PiecewiseLinear:
          E1: -1.7011
          E2: -1.0035
          d: 2
          pos1: 1.34
          pos2: 4.82
      - PiecewiseLinear:
          E1: -2.9939
          E2: -1.6464
          d: 2
          pos1: 6.32
          pos2: 8.38
      - PiecewiseLinear:
          E1: -0.3962
          E2: 4.9477
          d: 2
          pos1: 14.38
          pos2: 17.16
      - Sine:
          A: 0.3381
          dForce: 2
          dMod: 2
          k: 1
          phase: 2.9289
      - Sine:
          A: 0.9425
          dForce: 2
          dMod: 2
          k: 2
          phase: 5.8494
      - Sine:
          A: 3.3543
          dForce: 2
          dMod: 2
          k: 3
          phase: 4.1699
      - Sine:
          A: 5.0316
          dForce: 2
          dMod: 2
          k: 4
          phase: 1.6156
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: 3.5333