InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.5279
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 19.3802
    - 19.3802
    - 20
  T: 1.984
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 1.48
      - PiecewiseLinear:
          E1: -2.121
          E2: -0.1295
          d: 2
          pos1: 3.99
          pos2: 7.8
      - PiecewiseLinear:
          E1: 1.3763
          E2: 2.0465
          d: 2
          pos1: 5.13
          pos2: 9.35
      - PiecewiseLinear:
          E1: 1.4955
          E2: -0.7665
          d: 2
          pos1: 7.82
          pos2: 10.01
      - PiecewiseLinear:
          E1: -0.2866
          E2: 0.4291
          d: 2
          pos1: 14.3
          pos2: 17.31
      - Sine:
          A: 0.4122
          dForce: 2
          dMod: 2
          k: 1
          phase: 1.8051
      - Sine:
          A: 0.0949
          dForce: 2
          dMod: 2
          k: 2
          phase: 2.352
      - Sine:
          A: 1.2217
          dForce: 2
          dMod: 2
          k: 3
          phase: 1.0231
      - Sine:
          A: 3.1964
          dForce: 2
          dMod: 2
          k: 4
          phase: 4.2144
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -3.157