InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.2361
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 16.6388
    - 16.6388
    - 20
  T: 1.6611
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.68
      - PiecewiseLinear:
          E1: 1.4158
          E2: 1.2119
          d: 2
          pos1: 13.76
          pos2: 18.2
      - PiecewiseLinear:
          E1: -0.502
          E2: 3.8779
          d: 2
          pos1: 14.95
          pos2: 16.34
      - PiecewiseLinear:
          E1: -1.6615
          E2: -0.229
          d: 2
          pos1: 14.37
          pos2: 16.41
      - PiecewiseLinear:
          E1: -0.5691
          E2: -4.0252
          d: 2
          pos1: 13.84
          pos2: 16.98
      - Sine:
          A: 0.443
          dForce: 2
          dMod: 2
          k: 1
          phase: 1.7989
      - Sine:
          A: 1.1961
          dForce: 2
          dMod: 2
          k: 2
          phase: 1.8887
      - Sine:
          A: 2.0241
          dForce: 2
          dMod: 2
          k: 3
          phase: 5.7592
      - Sine:
          A: 2.2684
          dForce: 2
          dMod: 2
          k: 4
          phase: 2.1032
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -2.87