InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.5981
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 10.9976
    - 10.9976
    - 20
  T: 1.5105
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.62
      - PiecewiseLinear:
          E1: -0.8869
          E2: 0.7964
          d: 2
          pos1: 6.02
          pos2: 9.53
      - PiecewiseLinear:
          E1: 0.5588
          E2: -1.4098
          d: 2
          pos1: 1.22
          pos2: 3.57
      - PiecewiseLinear:
          E1: 1.9525
          E2: 2.8555
          d: 2
          pos1: 8.61
          pos2: 11.67
      - PiecewiseLinear:
          E1: 1.5386
          E2: -2.5
          d: 2
          pos1: 14.66
          pos2: 15.89
      - Sine:
          A: 0.2577
          dForce: 2
          dMod: 2
          k: 1
          phase: 5.7596
      - Sine:
          A: 1.0482
          dForce: 2
          dMod: 2
          k: 2
          phase: 2.1083
      - Sine:
          A: 0.5487
          dForce: 2
          dMod: 2
          k: 3
          phase: 0.3843
      - Sine:
          A: 0.4991
          dForce: 2
          dMod: 2
          k: 4
          phase: 4.772
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: 2.94