InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.8026
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 18.5236
    - 18.5236
    - 20
  T: 1.6421
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.53
      - PiecewiseLinear:
          E1: -1.8088
          E2: -5.2811
          d: 2
          pos1: 3.96
          pos2: 6.48
      - PiecewiseLinear:
          E1: 0.9219
          E2: 2.12
          d: 2
          pos1: 11.11
          pos2: 14.82
      - PiecewiseLinear:
          E1: 2.9503
          E2: 0.0667
          d: 2
          pos1: 2.38
          pos2: 6.99
      - PiecewiseLinear:
          E1: -2.0046
          E2: 2.1621
          d: 2
          pos1: 8.27
          pos2: 10.1
      - Sine:
          A: 0.2671
          dForce: 2
          dMod: 2
          k: 1
          phase: 0.5388
      - Sine:
          A: 1.1438
          dForce: 2
          dMod: 2
          k: 2
          phase: 5.917
      - Sine:
          A: 0.1718
          dForce: 2
          dMod: 2
          k: 3
          phase: 0.0574
      - Sine:
          A: 0.7437
          dForce: 2
          dMod: 2
          k: 4
          phase: 5.5222
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: 1.8337