InitParticles:
  - lattice:
      cell: fcc
      spacing: 2.1226
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 12.9863
    - 12.9863
    - 20
  T: 1.2609
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.84
      - PiecewiseLinear:
          E1: -2.3333
          E2: -1.1069
          d: 2
          pos1: 0.41
          pos2: 2.53
      - PiecewiseLinear:
          E1: -0.3003
          E2: -3.0508
          d: 2
          pos1: 6.66
          pos2: 9.85
      - PiecewiseLinear:
          E1: 1.2541
          E2: 0.422
          d: 2
          pos1: 11.98
          pos2: 16.65
      - PiecewiseLinear:
          E1: 0.4143
          E2: -0.2374
          d: 2
          pos1: 10.89
          pos2: 14.89
      - Sine:
          A: 0.0548
          dForce: 2
          dMod: 2
          k: 1
          phase: 0.4862
      - Sine:
          A: 1.2075
          dForce: 2
          dMod: 2
          k: 2
          phase: 3.821
      - Sine:
          A: 0.7864
          dForce: 2
          dMod: 2
          k: 3
          phase: 1.1786
      - Sine:
          A: 2.2611
          dForce: 2
          dMod: 2
          k: 4
          phase: 5.6827
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -3.7076