InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.9485
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 17.1609
    - 17.1609
    - 20
  T: 1.1127
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.63
      - PiecewiseLinear:
          E1: -0.3918
          E2: 0.9366
          d: 2
          pos1: 3.52
          pos2: 4.8
      - PiecewiseLinear:
          E1: 2.5998
          E2: 0.235
          d: 2
          pos1: 7.11
          pos2: 9.71
      - PiecewiseLinear:
          E1: -2.2887
          E2: 0.0096
          d: 2
          pos1: 14.51
          pos2: 18.15
      - PiecewiseLinear:
          E1: 3.5259
          E2: -0.9359
          d: 2
          pos1: 7.34
          pos2: 11.33
      - Sine:
          A: 0.038
          dForce: 2
          dMod: 2
          k: 1
          phase: 5.7024
      - Sine:
          A: 0.3643
          dForce: 2
          dMod: 2
          k: 2
          phase: 2.1719
      - Sine:
          A: 0.5151
          dForce: 2
          dMod: 2
          k: 3
          phase: 4.7988
      - Sine:
          A: 2.6229
          dForce: 2
          dMod: 2
          k: 4
          phase: 3.7844
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -5.6764