InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.3244
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 12.8739
    - 12.8739
    - 20
  T: 1.6789
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.44
      - PiecewiseLinear:
          E1: -1.6628
          E2: -1.2888
          d: 2
          pos1: 10.21
          pos2: 14.93
      - PiecewiseLinear:
          E1: 1.5395
          E2: -1.1127
          d: 2
          pos1: 11.85
          pos2: 12.86
      - PiecewiseLinear:
          E1: -0.6544
          E2: 0.725
          d: 2
          pos1: 12.57
          pos2: 13.59
      - PiecewiseLinear:
          E1: 0.8052
          E2: -1.277
          d: 2
          pos1: 12.62
          pos2: 15.56
      - Sine:
          A: 0.3689
          dForce: 2
          dMod: 2
          k: 1
          phase: 0.8708
      - Sine:
          A: 0.1727
          dForce: 2
          dMod: 2
          k: 2
          phase: 1.2455
      - Sine:
          A: 0.0025
          dForce: 2
          dMod: 2
          k: 3
          phase: 3.8989
      - Sine:
          A: 1.6625
          dForce: 2
          dMod: 2
          k: 4
          phase: 3.3765
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -2.7791