InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.181
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 14.6461
    - 14.6461
    - 20
  T: 1.8051
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 1.46
      - PiecewiseLinear:
          E1: 0.3351
          E2: 1.7788
          d: 2
          pos1: 11.72
          pos2: 14.69
      - PiecewiseLinear:
          E1: 1.0543
          E2: -2.3901
          d: 2
          pos1: 13.16
          pos2: 14.4
      - PiecewiseLinear:
          E1: -0.6431
          E2: 0.3723
          d: 2
          pos1: 5.85
          pos2: 7.96
      - PiecewiseLinear:
          E1: 1.8904
          E2: 2.749
          d: 2
          pos1: 2.58
          pos2: 6.53
      - Sine:
          A: 0.6387
          dForce: 2
          dMod: 2
          k: 1
          phase: 0.0669
      - Sine:
          A: 0.9998
          dForce: 2
          dMod: 2
          k: 2
          phase: 3.323
      - Sine:
          A: 0.2059
          dForce: 2
          dMod: 2
          k: 3
          phase: 2.9168
      - Sine:
          A: 1.4045
          dForce: 2
          dMod: 2
          k: 4
          phase: 3.9845
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: 2.4971