InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.8129
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 12.1838
    - 12.1838
    - 20
  T: 1.914
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.14
      - PiecewiseLinear:
          E1: -4.1856
          E2: -0.3201
          d: 2
          pos1: 7.62
          pos2: 11.83
      - PiecewiseLinear:
          E1: 1.9055
          E2: 0.7184
          d: 2
          pos1: 10.99
          pos2: 14.1
      - PiecewiseLinear:
          E1: -1.4861
          E2: -2.3607
          d: 2
          pos1: 9.73
          pos2: 13.31
      - PiecewiseLinear:
          E1: -0.2831
          E2: 1.3836
          d: 2
          pos1: 14.64
          pos2: 17.15
      - Sine:
          A: 0.4721
          dForce: 2
          dMod: 2
          k: 1
          phase: 2.8371
      - Sine:
          A: 0.6359
          dForce: 2
          dMod: 2
          k: 2
          phase: 2.1499
      - Sine:
          A: 0.0526
          dForce: 2
          dMod: 2
          k: 3
          phase: 4.2916
      - Sine:
          A: 0.6216
          dForce: 2
          dMod: 2
          k: 4
          phase: 0.1214
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -1.7748