InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.9229
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 12.6486
    - 12.6486
    - 20
  T: 1.2279
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 1.06
      - PiecewiseLinear:
          E1: -1.552
          E2: 2.6355
          d: 2
          pos1: 5.26
          pos2: 9.07
      - PiecewiseLinear:
          E1: -2.1553
          E2: -1.8875
          d: 2
          pos1: 7.97
          pos2: 11.44
      - PiecewiseLinear:
          E1: -1.5469
          E2: 3.7543
          d: 2
          pos1: 4.84
          pos2: 7.17
      - PiecewiseLinear:
          E1: -3.5019
          E2: -0.5472
          d: 2
          pos1: 14.92
          pos2: 19.88
      - Sine:
          A: 0.171
          dForce: 2
          dMod: 2
          k: 1
          phase: 1.8404
      - Sine:
          A: 1.8617
          dForce: 2
          dMod: 2
          k: 2
          phase: 2.4206
      - Sine:
          A: 1.9551
          dForce: 2
          dMod: 2
          k: 3
          phase: 0.222
      - Sine:
          A: 2.3963
          dForce: 2
          dMod: 2
          k: 4
          phase: 3.3409
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -0.7917