InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.1151
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 9.9318
    - 9.9318
    - 20
  T: 1.3093
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 1.02
      - PiecewiseLinear:
          E1: 0.0243
          E2: 6.053
          d: 2
          pos1: 14.84
          pos2: 17.11
      - PiecewiseLinear:
          E1: -3.6902
          E2: 0.2388
          d: 2
          pos1: 10.73
          pos2: 15.38
      - PiecewiseLinear:
          E1: 2.0967
          E2: -1.2708
          d: 2
          pos1: 5.75
          pos2: 9.23
      - PiecewiseLinear:
          E1: 1.4599
          E2: -1.3207
          d: 2
          pos1: 10.83
          pos2: 14.3
      - Sine:
          A: 0.046
          dForce: 2
          dMod: 2
          k: 1
          phase: 0.6217
      - Sine:
          A: 1.2679
          dForce: 2
          dMod: 2
          k: 2
          phase: 5.7167
      - Sine:
          A: 1.7044
          dForce: 2
          dMod: 2
          k: 3
          phase: 1.3744
      - Sine:
          A: 0.8639
          dForce: 2
          dMod: 2
          k: 4
          phase: 3.0204
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: 0.295