InitParticles:
  - lattice:
      cell: fcc
      spacing: 2.0042
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 6.6726
    - 6.6726
    - 20
  T: 1.4132
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.65
      - PiecewiseLinear:
          E1: -1.4026
          E2: 0.5778
          d: 2
          pos1: 6.09
          pos2: 8.51
      - PiecewiseLinear:
          E1: 0.022
          E2: -0.9159
          d: 2
          pos1: 0.62
          pos2: 2.61
      - PiecewiseLinear:
          E1: 2.8085
          E2: -2.4839
          d: 2
          pos1: 0.57
          pos2: 5.34
      - PiecewiseLinear:
          E1: 0.1194
          E2: -2.5915
          d: 2
          pos1: 10.63
          pos2: 15.47
      - Sine:
          A: 0.4965
          dForce: 2
          dMod: 2
          k: 1
          phase: 0.3391
      - Sine:
          A: 0.5996
          dForce: 2
          dMod: 2
          k: 2
          phase: 5.5968
      - Sine:
          A: 0.7408
          dForce: 2
          dMod: 2
          k: 3
          phase: 6.0662
      - Sine:
          A: 1.8397
          dForce: 2
          dMod: 2
          k: 4
          phase: 4.4586
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -0.2943