InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.6602
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 10.7238
    - 10.7238
    - 20
  T: 1.9707
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.6
      - PiecewiseLinear:
          E1: -0.1743
          E2: -0.9727
          d: 2
          pos1: 10.9
          pos2: 14.65
      - PiecewiseLinear:
          E1: -1.2712
          E2: -0.3537
          d: 2
          pos1: 1.83
          pos2: 3.59
      - PiecewiseLinear:
          E1: 0.9425
          E2: 0.9213
          d: 2
          pos1: 9.78
          pos2: 13.02
      - PiecewiseLinear:
          E1: 0.5434
          E2: 0.683
          d: 2
          pos1: 13.8
          pos2: 15.24
      - Sine:
          A: 0.0939
          dForce: 2
          dMod: 2
          k: 1
          phase: 2.294
      - Sine:
          A: 0.604
          dForce: 2
          dMod: 2
          k: 2
          phase: 6.1888
      - Sine:
          A: 1.7425
          dForce: 2
          dMod: 2
          k: 3
          phase: 4.6972
      - Sine:
          A: 2.0354
          dForce: 2
          dMod: 2
          k: 4
          phase: 3.9971
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -1.005