InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.1867
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 18.072
    - 18.072
    - 20
  T: 1.7061
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.65
      - PiecewiseLinear:
          E1: -1.0896
          E2: -1.0132
          d: 2
          pos1: 7.66
          pos2: 10.11
      - PiecewiseLinear:
          E1: 3.1004
          E2: -0.3627
          d: 2
          pos1: 8.85
          pos2: 12.38
      - PiecewiseLinear:
          E1: -2.3878
          E2: 1.8688
          d: 2
          pos1: 14.06
          pos2: 16.9
      - PiecewiseLinear:
          E1: -1.6387
          E2: -1.7483
          d: 2
          pos1: 13.78
          pos2: 16.62
      - Sine:
          A: 0.2174
          dForce: 2
          dMod: 2
          k: 1
          phase: 5.563
      - Sine:
          A: 0.0578
          dForce: 2
          dMod: 2
          k: 2
          phase: 5.8159
      - Sine:
          A: 0.325
          dForce: 2
          dMod: 2
          k: 3
          phase: 2.1899
      - Sine:
          A: 2.0109
          dForce: 2
          dMod: 2
          k: 4
          phase: 2.434
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -1.9592