InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.7878
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 17.8768
    - 17.8768
    - 20
  T: 1.0794
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 1.47
      - PiecewiseLinear:
          E1: -2.6216
          E2: 0.1655
          d: 2
          pos1: 7.45
          pos2: 10.96
      - PiecewiseLinear:
          E1: -0.1879
          E2: 1.3555
          d: 2
          pos1: 13.94
          pos2: 18.03
      - PiecewiseLinear:
          E1: -0.1001
          E2: -0.7201
          d: 2
          pos1: 12.72
          pos2: 16.66
      - PiecewiseLinear:
          E1: -1.1411
          E2: -3.3601
          d: 2
          pos1: 3.23
          pos2: 4.66
      - Sine:
          A: 0.1871
          dForce: 2
          dMod: 2
          k: 1
          phase: 4.4129
      - Sine:
          A: 0.8656
          dForce: 2
          dMod: 2
          k: 2
          phase: 3.2729
      - Sine:
          A: 0.772
          dForce: 2
          dMod: 2
          k: 3
          phase: 3.7541
      - Sine:
          A: 1.0681
          dForce: 2
          dMod: 2
          k: 4
          phase: 2.4612
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -1.1147