InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.3411
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 16.2518
    - 16.2518
    - 20
  T: 1.5499
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.18
      - PiecewiseLinear:
          E1: -0.8293
          E2: 0.7221
          d: 2
          pos1: 14.44
          pos2: 18.17
      - PiecewiseLinear:
          E1: 4.4828
          E2: 0.6152
          d: 2
          pos1: 3.63
          pos2: 6.12
      - PiecewiseLinear:
          E1: -2.6858
          E2: -0.6402
          d: 2
          pos1: 0.08
          pos2: 4.27
      - PiecewiseLinear:
          E1: -3.2599
          E2: -1.5153
          d: 2
          pos1: 5.86
          pos2: 9.6
      - Sine:
          A: 0.371
          dForce: 2
          dMod: 2
          k: 1
          phase: 3.7792
      - Sine:
          A: 1.7682
          dForce: 2
          dMod: 2
          k: 2
          phase: 3.1292
      - Sine:
          A: 0.5306
          dForce: 2
          dMod: 2
          k: 3
          phase: 3.4394
      - Sine:
          A: 1.8121
          dForce: 2
          dMod: 2
          k: 4
          phase: 1.0354
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -3.4414