InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.7569
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 8.1499
    - 8.1499
    - 20
  T: 1.6382
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.57
      - PiecewiseLinear:
          E1: 1.443
          E2: -1.9704
          d: 2
          pos1: 14.65
          pos2: 17.48
      - PiecewiseLinear:
          E1: 0.3909
          E2: 0.5966
          d: 2
          pos1: 10.79
          pos2: 14.75
      - PiecewiseLinear:
          E1: 1.9494
          E2: 0.2441
          d: 2
          pos1: 6.52
          pos2: 9.27
      - PiecewiseLinear:
          E1: -2.0786
          E2: -0.4219
          d: 2
          pos1: 8.41
          pos2: 10.44
      - Sine:
          A: 0.1339
          dForce: 2
          dMod: 2
          k: 1
          phase: 1.7462
      - Sine:
          A: 1.0201
          dForce: 2
          dMod: 2
          k: 2
          phase: 3.48
      - Sine:
          A: 0.7897
          dForce: 2
          dMod: 2
          k: 3
          phase: 2.3425
      - Sine:
          A: 3.6541
          dForce: 2
          dMod: 2
          k: 4
          phase: 4.0423
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -5.0116