InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.5177
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 19.4841
    - 19.4841
    - 20
  T: 1.9967
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.82
      - PiecewiseLinear:
          E1: -0.2078
          E2: 0.5436
          d: 2
          pos1: 9.21
          pos2: 12.82
      - PiecewiseLinear:
          E1: 4.6866
          E2: -1.3767
          d: 2
          pos1: 3.01
          pos2: 6.03
      - PiecewiseLinear:
          E1: -0.9821
          E2: 3.7485
          d: 2
          pos1: 3.48
          pos2: 4.81
      - PiecewiseLinear:
          E1: -2.0138
          E2: -3.1635
          d: 2
          pos1: 1.92
          pos2: 4.67
      - Sine:
          A: 0.2416
          dForce: 2
          dMod: 2
          k: 1
          phase: 3.5976
      - Sine:
          A: 1.5257
          dForce: 2
          dMod: 2
          k: 2
          phase: 5.543
      - Sine:
          A: 1.6055
          dForce: 2
          dMod: 2
          k: 3
          phase: 5.7239
      - Sine:
          A: 1.0203
          dForce: 2
          dMod: 2
          k: 4
          phase: 4.051
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -3.5851