InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.4306
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 7.7794
    - 7.7794
    - 20
  T: 1.5498
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.66
      - PiecewiseLinear:
          E1: 0.1433
          E2: 1.2909
          d: 2
          pos1: 4.94
          pos2: 8.01
      - PiecewiseLinear:
          E1: -2.0596
          E2: -1.83
          d: 2
          pos1: 12.82
          pos2: 17.79
      - PiecewiseLinear:
          E1: 0.0995
          E2: -0.2871
          d: 2
          pos1: 9.05
          pos2: 12.84
      - PiecewiseLinear:
          E1: -0.8416
          E2: 0.0696
          d: 2
          pos1: 4.67
          pos2: 8.23
      - Sine:
          A: 0.047
          dForce: 2
          dMod: 2
          k: 1
          phase: 3.8272
      - Sine:
          A: 0.4857
          dForce: 2
          dMod: 2
          k: 2
          phase: 6.1143
      - Sine:
          A: 0.5878
          dForce: 2
          dMod: 2
          k: 3
          phase: 1.1015
      - Sine:
          A: 0.6518
          dForce: 2
          dMod: 2
          k: 4
          phase: 3.8735
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -4.3876