InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.5492
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 11.65
    - 11.65
    - 20
  T: 1.1642
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.32
      - PiecewiseLinear:
          E1: 1.7397
          E2: 2.8252
          d: 2
          pos1: 5.62
          pos2: 7.48
      - PiecewiseLinear:
          E1: -1.2425
          E2: 2.1178
          d: 2
          pos1: 3.16
          pos2: 4.31
      - PiecewiseLinear:
          E1: 2.8695
          E2: 1.8397
          d: 2
          pos1: 4.04
          pos2: 7.81
      - PiecewiseLinear:
          E1: -2.0672
          E2: -1.4794
          d: 2
          pos1: 4.26
          pos2: 7.6
      - Sine:
          A: 0.3716
          dForce: 2
          dMod: 2
          k: 1
          phase: 2.4755
      - Sine:
          A: 0.1798
          dForce: 2
          dMod: 2
          k: 2
          phase: 4.5148
      - Sine:
          A: 0.0896
          dForce: 2
          dMod: 2
          k: 3
          phase: 1.4418
      - Sine:
          A: 1.1766
          dForce: 2
          dMod: 2
          k: 4
          phase: 3.4354
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -0.1932