InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.0636
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 19.589
    - 19.589
    - 20
  T: 1.9004
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.23
      - PiecewiseLinear:
          E1: -0.2098
          E2: -1.52
          d: 2
          pos1: 4.69
          pos2: 7.19
      - PiecewiseLinear:
          E1: -0.5402
          E2: 0.9362
          d: 2
          pos1: 6.01
          pos2: 7.61
      - PiecewiseLinear:
          E1: -1.1597
          E2: 0.0306
          d: 2
          pos1: 10.5
          pos2: 12.2
      - PiecewiseLinear:
          E1: -1.5799
          E2: -1.8514
          d: 2
          pos1: 13.63
          pos2: 17.33
      - Sine:
          A: 0.1048
          dForce: 2
          dMod: 2
          k: 1
          phase: 4.6708
      - Sine:
          A: 1.0288
          dForce: 2
          dMod: 2
          k: 2
          phase: 4.8434
      - Sine:
          A: 4.7462
          dForce: 2
          dMod: 2
          k: 3
          phase: 5.6215
      - Sine:
          A: 0.362
          dForce: 2
          dMod: 2
          k: 4
          phase: 3.1029
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -4.4422