InitParticles:
  - lattice:
      cell: fcc
      spacing: 2.1289
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 5.5432
    - 5.5432
    - 20
  T: 1.3592
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.36
      - PiecewiseLinear:
          E1: 0.8703
          E2: -1.4741
          d: 2
          pos1: 14.74
          pos2: 19.42
      - PiecewiseLinear:
          E1: 2.9134
          E2: -0.6107
          d: 2
          pos1: 14.76
          pos2: 18.32
      - PiecewiseLinear:
          E1: 3.7868
          E2: -2.7919
          d: 2
          pos1: 6.77
          pos2: 11.63
      - PiecewiseLinear:
          E1: 0.9402
          E2: 2.8995
          d: 2
          pos1: 11.84
          pos2: 13.72
      - Sine:
          A: 0.3434
          dForce: 2
          dMod: 2
          k: 1
          phase: 0.6946
      - Sine:
          A: 2.0726
          dForce: 2
          dMod: 2
          k: 2
          phase: 4.3783
      - Sine:
          A: 0.3601
          dForce: 2
          dMod: 2
          k: 3
          phase: 3.8903
      - Sine:
          A: 0.8708
          dForce: 2
          dMod: 2
          k: 4
          phase: 5.5094
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -2.4613