InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.0528
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 7.6675
    - 7.6675
    - 20
  T: 1.4299
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 1.25
      - PiecewiseLinear:
          E1: -1.3834
          E2: -0.0757
          d: 2
          pos1: 12.42
          pos2: 13.93
      - PiecewiseLinear:
          E1: -2.4066
          E2: -4.5995
          d: 2
          pos1: 10.4
          pos2: 14.48
      - PiecewiseLinear:
          E1: -2.4943
          E2: 1.4274
          d: 2
          pos1: 2.86
          pos2: 5.42
      - PiecewiseLinear:
          E1: -4.0197
          E2: -3.2581
          d: 2
          pos1: 0.37
          pos2: 3.38
      - Sine:
          A: 0.547
          dForce: 2
          dMod: 2
          k: 1
          phase: 2.7853
      - Sine:
          A: 0.4285
          dForce: 2
          dMod: 2
          k: 2
          phase: 1.4804
      - Sine:
          A: 1.0827
          dForce: 2
          dMod: 2
          k: 3
          phase: 3.5456
      - Sine:
          A: 1.3224
          dForce: 2
          dMod: 2
          k: 4
          phase: 5.3853
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -0.7611