InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.8802
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 19.7303
    - 19.7303
    - 20
  T: 1.3461
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 1.27
      - PiecewiseLinear:
          E1: -3.0847
          E2: -2.5105
          d: 2
          pos1: 7.27
          pos2: 10.23
      - PiecewiseLinear:
          E1: 0.5771
          E2: 1.2161
          d: 2
          pos1: 0.59
          pos2: 5.53
      - PiecewiseLinear:
          E1: 0.2884
          E2: -0.4477
          d: 2
          pos1: 13.44
          pos2: 18.39
      - PiecewiseLinear:
          E1: -0.3248
          E2: 1.17
          d: 2
          pos1: 12.45
          pos2: 15.5
      - Sine:
          A: 0.2066
          dForce: 2
          dMod: 2
          k: 1
          phase: 1.5937
      - Sine:
          A: 0.4955
          dForce: 2
          dMod: 2
          k: 2
          phase: 2.6914
      - Sine:
          A: 1.6214
          dForce: 2
          dMod: 2
          k: 3
          phase: 4.0754
      - Sine:
          A: 2.367
          dForce: 2
          dMod: 2
          k: 4
          phase: 4.0404
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -2.614