InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.6939
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 7.9667
    - 7.9667
    - 20
  T: 1.0685
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.45
      - PiecewiseLinear:
          E1: 2.1153
          E2: -2.0728
          d: 2
          pos1: 9.98
          pos2: 14.74
      - PiecewiseLinear:
          E1: 3.1021
          E2: 2.3258
          d: 2
          pos1: 14.51
          pos2: 18.9
      - PiecewiseLinear:
          E1: -0.4061
          E2: 2.0155
          d: 2
          pos1: 6.51
          pos2: 7.86
      - PiecewiseLinear:
          E1: 0.3963
          E2: -0.0676
          d: 2
          pos1: 8.11
          pos2: 11.78
      - Sine:
          A: 0.6327
          dForce: 2
          dMod: 2
          k: 1
          phase: 4.7201
      - Sine:
          A: 0.97
          dForce: 2
          dMod: 2
          k: 2
          phase: 0.8326
      - Sine:
          A: 0.1897
          dForce: 2
          dMod: 2
          k: 3
          phase: 2.4154
      - Sine:
          A: 1.0903
          dForce: 2
          dMod: 2
          k: 4
          phase: 0.3592
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: 0.5682