InitParticles:
  - lattice:
      cell: fcc
      spacing: 2.1942
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 6.2572
    - 6.2572
    - 20
  T: 1.351
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 1.26
      - PiecewiseLinear:
          E1: -0.455
          E2: -0.0245
          d: 2
          pos1: 3.76
          pos2: 8.69
      - PiecewiseLinear:
          E1: -1.1797
          E2: 0.8559
          d: 2
          pos1: 5.27
          pos2: 6.82
      - PiecewiseLinear:
          E1: -1.5683
          E2: 1.557
          d: 2
          pos1: 9.72
          pos2: 13.61
      - PiecewiseLinear:
          E1: 1.5535
          E2: 0.6748
          d: 2
          pos1: 3.87
          pos2: 5.78
      - Sine:
          A: 0.4306
          dForce: 2
          dMod: 2
          k: 1
          phase: 0.1062
      - Sine:
          A: 0.0296
          dForce: 2
          dMod: 2
          k: 2
          phase: 2.2582
      - Sine:
          A: 0.2312
          dForce: 2
          dMod: 2
          k: 3
          phase: 5.4505
      - Sine:
          A: 0.3578
          dForce: 2
          dMod: 2
          k: 4
          phase: 4.6408
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: 1.1999