InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.999
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 6.041
    - 6.041
    - 20
  T: 1.3942
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.13
      - PiecewiseLinear:
          E1: -2.7575
          E2: 1.6848
          d: 2
          pos1: 14.11
          pos2: 16.53
      - PiecewiseLinear:
          E1: -2.6816
          E2: 3.1813
          d: 2
          pos1: 5.46
          pos2: 9.03
      - PiecewiseLinear:
          E1: 0.2921
          E2: -0.9559
          d: 2
          pos1: 3.34
          pos2: 7.26
      - PiecewiseLinear:
          E1: 0.3437
          E2: -0.9713
          d: 2
          pos1: 12.62
          pos2: 15.1
      - Sine:
          A: 0.1884
          dForce: 2
          dMod: 2
          k: 1
          phase: 0.0682
      - Sine:
          A: 1.3036
          dForce: 2
          dMod: 2
          k: 2
          phase: 0.5308
      - Sine:
          A: 1.3838
          dForce: 2
          dMod: 2
          k: 3
          phase: 0.0185
      - Sine:
          A: 2.1181
          dForce: 2
          dMod: 2
          k: 4
          phase: 2.1813
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: 2.222