InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.0946
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 15.2975
    - 15.2975
    - 20
  T: 1.8604
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 1.48
      - PiecewiseLinear:
          E1: 1.6246
          E2: 2.5334
          d: 2
          pos1: 14.72
          pos2: 19.53
      - PiecewiseLinear:
          E1: -1.0448
          E2: -0.8811
          d: 2
          pos1: 1.26
          pos2: 3.68
      - PiecewiseLinear:
          E1: 0.2231
          E2: 0.2405
          d: 2
          pos1: 11.6
          pos2: 15.33
      - PiecewiseLinear:
          E1: -2.4005
          E2: 1.3668
          d: 2
          pos1: 9.61
          pos2: 10.76
      - Sine:
          A: 0.2485
          dForce: 2
          dMod: 2
          k: 1
          phase: 1.4429
      - Sine:
          A: 0.9479
          dForce: 2
          dMod: 2
          k: 2
          phase: 0.2552
      - Sine:
          A: 0.3559
          dForce: 2
          dMod: 2
          k: 3
          phase: 5.6059
      - Sine:
          A: 2.4415
          dForce: 2
          dMod: 2
          k: 4
          phase: 2.8215
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -2.983