InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.5075
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 18.1103
    - 18.1103
    - 20
  T: 1.6069
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 1.17
      - PiecewiseLinear:
          E1: -0.1148
          E2: 0.1196
          d: 2
          pos1: 13.62
          pos2: 16.78
      - PiecewiseLinear:
          E1: -4.3955
          E2: 1.052
          d: 2
          pos1: 0.97
          pos2: 3.83
      - PiecewiseLinear:
          E1: 0.6194
          E2: 0.0806
          d: 2
          pos1: 3.29
          pos2: 6.86
      - PiecewiseLinear:
          E1: -2.3449
          E2: 0.516
          d: 2
          pos1: 5.75
          pos2: 8.89
      - Sine:
          A: 0.3091
          dForce: 2
          dMod: 2
          k: 1
          phase: 3.5841
      - Sine:
          A: 0.311
          dForce: 2
          dMod: 2
          k: 2
          phase: 1.668
      - Sine:
          A: 0.1086
          dForce: 2
          dMod: 2
          k: 3
          phase: 6.1275
      - Sine:
          A: 0.8082
          dForce: 2
          dMod: 2
          k: 4
          phase: 5.9444
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -2.488