InitParticles:
  - lattice:
      cell: fcc
      spacing: 2.166
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 15.3386
    - 15.3386
    - 20
  T: 1.8243
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.8
      - PiecewiseLinear:
          E1: -0.777
          E2: -1.5688
          d: 2
          pos1: 1.6
          pos2: 3.92
      - PiecewiseLinear:
          E1: -0.7442
          E2: -0.6012
          d: 2
          pos1: 7.92
          pos2: 10.42
      - PiecewiseLinear:
          E1: 2.6106
          E2: 0.2837
          d: 2
          pos1: 0.77
          pos2: 3.69
      - PiecewiseLinear:
          E1: 3.0755
          E2: 2.2574
          d: 2
          pos1: 6.09
          pos2: 10.0
      - Sine:
          A: 0.3157
          dForce: 2
          dMod: 2
          k: 1
          phase: 4.4249
      - Sine:
          A: 0.3936
          dForce: 2
          dMod: 2
          k: 2
          phase: 4.7352
      - Sine:
          A: 1.8086
          dForce: 2
          dMod: 2
          k: 3
          phase: 6.1339
      - Sine:
          A: 0.0219
          dForce: 2
          dMod: 2
          k: 4
          phase: 5.4401
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -6.8181