InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.5527
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 7.4066
    - 7.4066
    - 20
  T: 1.2774
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 1.25
      - PiecewiseLinear:
          E1: -1.2618
          E2: -0.9543
          d: 2
          pos1: 7.59
          pos2: 11.66
      - PiecewiseLinear:
          E1: 0.2691
          E2: -5.0437
          d: 2
          pos1: 12.16
          pos2: 13.88
      - PiecewiseLinear:
          E1: 1.7793
          E2: 0.5591
          d: 2
          pos1: 12.65
          pos2: 15.16
      - PiecewiseLinear:
          E1: 1.9797
          E2: 1.0601
          d: 2
          pos1: 9.36
          pos2: 12.97
      - Sine:
          A: 0.022
          dForce: 2
          dMod: 2
          k: 1
          phase: 4.5638
      - Sine:
          A: 0.314
          dForce: 2
          dMod: 2
          k: 2
          phase: 1.315
      - Sine:
          A: 1.0031
          dForce: 2
          dMod: 2
          k: 3
          phase: 1.7313
      - Sine:
          A: 1.4742
          dForce: 2
          dMod: 2
          k: 4
          phase: 4.528
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -5.0754