InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.1491
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 8.0419
    - 8.0419
    - 20
  T: 1.1289
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.31
      - PiecewiseLinear:
          E1: 1.9285
          E2: 1.0132
          d: 2
          pos1: 7.71
          pos2: 9.44
      - PiecewiseLinear:
          E1: 1.0941
          E2: 2.1147
          d: 2
          pos1: 3.67
          pos2: 6.72
      - PiecewiseLinear:
          E1: -5.0655
          E2: -1.9652
          d: 2
          pos1: 8.48
          pos2: 12.39
      - PiecewiseLinear:
          E1: -1.1994
          E2: -1.1884
          d: 2
          pos1: 13.02
          pos2: 17.86
      - Sine:
          A: 0.428
          dForce: 2
          dMod: 2
          k: 1
          phase: 2.0595
      - Sine:
          A: 0.5483
          dForce: 2
          dMod: 2
          k: 2
          phase: 4.6251
      - Sine:
          A: 2.0245
          dForce: 2
          dMod: 2
          k: 3
          phase: 6.2212
      - Sine:
          A: 0.0866
          dForce: 2
          dMod: 2
          k: 4
          phase: 5.4605
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -6.3866