InitParticles:
  - lattice:
      cell: fcc
      spacing: 2.1639
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 11.8693
    - 11.8693
    - 20
  T: 1.0946
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.37
      - PiecewiseLinear:
          E1: 1.6198
          E2: 0.1091
          d: 2
          pos1: 0.77
          pos2: 3.74
      - PiecewiseLinear:
          E1: -0.1068
          E2: 2.2396
          d: 2
          pos1: 12.44
          pos2: 16.1
      - PiecewiseLinear:
          E1: 1.4058
          E2: 1.6139
          d: 2
          pos1: 4.6
          pos2: 6.99
      - PiecewiseLinear:
          E1: -0.454
          E2: 2.8601
          d: 2
          pos1: 1.39
          pos2: 5.11
      - Sine:
          A: 0.2187
          dForce: 2
          dMod: 2
          k: 1
          phase: 2.5682
      - Sine:
          A: 0.5451
          dForce: 2
          dMod: 2
          k: 2
          phase: 1.1766
      - Sine:
          A: 1.0696
          dForce: 2
          dMod: 2
          k: 3
          phase: 2.3337
      - Sine:
          A: 2.3217
          dForce: 2
          dMod: 2
          k: 4
          phase: 5.6254
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -2.8591