InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.3489
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 16.1848
    - 16.1848
    - 20
  T: 1.006
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.48
      - PiecewiseLinear:
          E1: 0.0958
          E2: 1.6471
          d: 2
          pos1: 14.55
          pos2: 18.27
      - PiecewiseLinear:
          E1: -3.0746
          E2: 3.3406
          d: 2
          pos1: 0.47
          pos2: 4.72
      - PiecewiseLinear:
          E1: 2.2235
          E2: 1.1076
          d: 2
          pos1: 2.53
          pos2: 3.61
      - PiecewiseLinear:
          E1: 0.6503
          E2: 0.1778
          d: 2
          pos1: 4.62
          pos2: 5.81
      - Sine:
          A: 0.4682
          dForce: 2
          dMod: 2
          k: 1
          phase: 1.9178
      - Sine:
          A: 0.2412
          dForce: 2
          dMod: 2
          k: 2
          phase: 1.0257
      - Sine:
          A: 1.3276
          dForce: 2
          dMod: 2
          k: 3
          phase: 5.5713
      - Sine:
          A: 2.5563
          dForce: 2
          dMod: 2
          k: 4
          phase: 5.7256
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: 0.4618