InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.9573
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 10.3618
    - 10.3618
    - 20
  T: 1.4011
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.65
      - PiecewiseLinear:
          E1: -1.3414
          E2: -0.1065
          d: 2
          pos1: 13.31
          pos2: 16.51
      - PiecewiseLinear:
          E1: -0.4658
          E2: 0.1563
          d: 2
          pos1: 4.09
          pos2: 6.06
      - PiecewiseLinear:
          E1: 1.4242
          E2: 0.9789
          d: 2
          pos1: 11.28
          pos2: 14.15
      - PiecewiseLinear:
          E1: -1.7259
          E2: 1.0988
          d: 2
          pos1: 11.95
          pos2: 15.77
      - Sine:
          A: 0.6404
          dForce: 2
          dMod: 2
          k: 1
          phase: 0.236
      - Sine:
          A: 0.2729
          dForce: 2
          dMod: 2
          k: 2
          phase: 1.4809
      - Sine:
          A: 1.5523
          dForce: 2
          dMod: 2
          k: 3
          phase: 2.3931
      - Sine:
          A: 1.4249
          dForce: 2
          dMod: 2
          k: 4
          phase: 5.7063
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -5.9387