InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.7839
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 6.4974
    - 6.4974
    - 20
  T: 1.8046
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.42
      - PiecewiseLinear:
          E1: 4.8011
          E2: 1.8447
          d: 2
          pos1: 13.64
          pos2: 17.64
      - PiecewiseLinear:
          E1: 1.4622
          E2: 3.1442
          d: 2
          pos1: 2.34
          pos2: 7.12
      - PiecewiseLinear:
          E1: 1.3979
          E2: 0.4997
          d: 2
          pos1: 11.23
          pos2: 14.67
      - PiecewiseLinear:
          E1: -1.9145
          E2: -2.4526
          d: 2
          pos1: 11.08
          pos2: 15.89
      - Sine:
          A: 0.1046
          dForce: 2
          dMod: 2
          k: 1
          phase: 3.424
      - Sine:
          A: 0.4036
          dForce: 2
          dMod: 2
          k: 2
          phase: 4.7032
      - Sine:
          A: 0.9798
          dForce: 2
          dMod: 2
          k: 3
          phase: 2.3436
      - Sine:
          A: 0.5215
          dForce: 2
          dMod: 2
          k: 4
          phase: 2.7429
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -6.6492