InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.5999
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 19.0917
    - 19.0917
    - 20
  T: 1.3888
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 1.41
      - PiecewiseLinear:
          E1: 3.2139
          E2: -0.9721
          d: 2
          pos1: 9.56
          pos2: 11.14
      - PiecewiseLinear:
          E1: 1.2481
          E2: -0.7568
          d: 2
          pos1: 10.19
          pos2: 13.72
      - PiecewiseLinear:
          E1: -1.597
          E2: -3.6191
          d: 2
          pos1: 2.73
          pos2: 7.0
      - PiecewiseLinear:
          E1: -2.8151
          E2: 0.0036
          d: 2
          pos1: 4.45
          pos2: 8.43
      - Sine:
          A: 0.4239
          dForce: 2
          dMod: 2
          k: 1
          phase: 2.6198
      - Sine:
          A: 0.1331
          dForce: 2
          dMod: 2
          k: 2
          phase: 4.7302
      - Sine:
          A: 0.3835
          dForce: 2
          dMod: 2
          k: 3
          phase: 5.4262
      - Sine:
          A: 0.8365
          dForce: 2
          dMod: 2
          k: 4
          phase: 5.1199
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -0.4996