InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.9156
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 5.3477
    - 5.3477
    - 20
  T: 1.4309
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 1.14
      - PiecewiseLinear:
          E1: 0.9905
          E2: -0.3338
          d: 2
          pos1: 11.87
          pos2: 15.27
      - PiecewiseLinear:
          E1: -2.8984
          E2: -1.369
          d: 2
          pos1: 3.13
          pos2: 5.12
      - PiecewiseLinear:
          E1: 0.3867
          E2: -0.9537
          d: 2
          pos1: 7.67
          pos2: 12.18
      - PiecewiseLinear:
          E1: -0.66
          E2: -2.9299
          d: 2
          pos1: 12.22
          pos2: 16.26
      - Sine:
          A: 0.0001
          dForce: 2
          dMod: 2
          k: 1
          phase: 3.6043
      - Sine:
          A: 0.0076
          dForce: 2
          dMod: 2
          k: 2
          phase: 5.9513
      - Sine:
          A: 0.5123
          dForce: 2
          dMod: 2
          k: 3
          phase: 5.2902
      - Sine:
          A: 0.3959
          dForce: 2
          dMod: 2
          k: 4
          phase: 5.6003
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: 0.131