InitParticles:
  - lattice:
      cell: fcc
      spacing: 1.5611
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 19.5626
    - 19.5626
    - 20
  T: 1.8452
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 0.53
      - PiecewiseLinear:
          E1: 3.2729
          E2: 0.021
          d: 2
          pos1: 6.32
          pos2: 9.68
      - PiecewiseLinear:
          E1: 0.6994
          E2: -0.8641
          d: 2
          pos1: 1.88
          pos2: 3.41
      - PiecewiseLinear:
          E1: -3.8192
          E2: -0.5707
          d: 2
          pos1: 4.25
          pos2: 5.42
      - PiecewiseLinear:
          E1: -3.4554
          E2: 1.7877
          d: 2
          pos1: 9.9
          pos2: 14.86
      - Sine:
          A: 0.0313
          dForce: 2
          dMod: 2
          k: 1
          phase: 4.0662
      - Sine:
          A: 1.0402
          dForce: 2
          dMod: 2
          k: 2
          phase: 6.2782
      - Sine:
          A: 0.4858
          dForce: 2
          dMod: 2
          k: 3
          phase: 1.6276
      - Sine:
          A: 3.1195
          dForce: 2
          dMod: 2
          k: 4
          phase: 1.7614
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -4.0013