InitParticles:
  - lattice:
      cell: fcc
      spacing: 2.1659
Integrator:
  MonteCarloGrandCanonical:
    dx: 0.1
Stages:
  - steps: 1e6
  - Observables:
      Onebody:
        bins:
          - 1
          - 1
          - 2000
        keys:
          - 1
          - Eext
    steps: 1e9
System:
  L:
    - 10.3156
    - 10.3156
    - 20
  T: 1.7755
  interaction:
    external:
      - WallsHard:
          d: 2
          width: 1.14
      - PiecewiseLinear:
          E1: -1.532
          E2: -0.1952
          d: 2
          pos1: 2.39
          pos2: 4.43
      - PiecewiseLinear:
          E1: -2.766
          E2: -3.1554
          d: 2
          pos1: 2.95
          pos2: 4.72
      - PiecewiseLinear:
          E1: -1.7886
          E2: -3.0241
          d: 2
          pos1: 7.56
          pos2: 10.19
      - PiecewiseLinear:
          E1: -0.9891
          E2: -0.2821
          d: 2
          pos1: 11.19
          pos2: 13.49
      - Sine:
          A: 0.1807
          dForce: 2
          dMod: 2
          k: 1
          phase: 3.4248
      - Sine:
          A: 0.8387
          dForce: 2
          dMod: 2
          k: 2
          phase: 4.8862
      - Sine:
          A: 1.0001
          dForce: 2
          dMod: 2
          k: 3
          phase: 1.7281
      - Sine:
          A: 1.0412
          dForce: 2
          dMod: 2
          k: 4
          phase: 5.1876
    internal:
      LJ:
        cutoff: 2.5
        shift: false
  mu: -5.4935